package com.github.antego.util;

public enum MetricName {
    POST_REQUEST_TIME,
    GET_REQUEST,
    POST_REQUEST,
    REBALANCE,
    REBALANCE_TIME,
    REMOTE_GET_TIME,
    REMOTE_POST_POST,
    STORAGE_PUT,
    STORAGE_GET,
    ERROR,
    REFRESH_CLUSTER_STATE,
    REMOTE_GET, REMOTE_POST, STORAGE_GET_POST, STORAGE_GET_TIME, STORAGE_PUT_TIME, GET_REQUEST_TIME
}
