package com.github.antego.util;

public enum MetricName {
    POST_REQUEST, GET_REQUESTS, POST_REQUESTS, REBALANCES, REMOTE_GET, REMOTE_POST, STORAGE_PUT, STORAGE_GET, ERROR, REFRESH_CLUSTER_STATE, GET_REQUEST
}
