{
 "title": "Metrics Paradise",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Storage rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "metrics-paradise.*.STORAGE_PUT.m1_rate"
    },
    {
     "target": "metrics-paradise.*.STORAGE_GET.m15_rate"
    }
   ]
  },
  {
   "title": "Storage latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "metrics-paradise.*.STORAGE_PUT_TIME.p50"
    },
    {
     "target": "metrics-paradise.*.STORAGE_GET_TIME.p50"
    }
   ]
  },
  {
   "title": "API requests rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "metrics-paradise.*.POST_REQUEST.m5_rate"
    },
    {
     "target": "metrics-paradise.*.GET_REQUEST.m1_rate"
    }
   ]
  },
  {
   "title": "API times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "metrics-paradise.*.POST_REQUEST_TIME.p50"
    },
    {
     "target": "metrics-paradise.*.GET_REQUEST_TIME.p50"
    }
   ]
  },
  {
   "title": "Remote requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "metrics-paradise.*.REMOTE_GET.m1_rate"
    },
    {
     "target": "metrics-paradise.*.REMOTE_POST.m1_rate"
    }
   ]
  },
  {
   "title": "Remote requests times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "metrics-paradise.*.REMOTE_GET_TIME.m5_rate"
    },
    {
     "target": "metrics-paradise.*.REMOTE_POST_TIME.p50"
    }
   ]
  },
  {
   "title": "Rebalance time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "metrics-paradise.*.REBALANCE_TIME.p50"
    }
   ]
  }
 ]
}